import React from 'react'
import NavigationPath from '../../components/navigation/navigation'
import Welcome from '@/app/components/welcome'
import Block from '@/app/components/block'

export const metadata = {
    title: 'Osvětlení a Svítidla',
}

const LampsAndLights = () => {
    return (
        <>
            <NavigationPath path={["Home", "Naše služby", "Osvětlení, svítidla"]} links={["/", "#", "/nase-sluzby/osvetleni-svitidla"]} />
            <Welcome heading="Nejvhodnější osvětlení je denní světlo" text="Vlastní výroba nábytku je součástí realizací našich návrhů interiérů, jak pro komerční tak soukromou klientelu. Jedná se o kuchyňské linky, vestavěné skříně, obývací sestavy, kancelářský nábytek." />
            <Block isRight={false} image="/static/osvetleni/svetlo.jpg" heading="Svítidla" text="V rámci našich služeb při vytvoření návrhů interiérů i následné vlastní realizaci spolupracujeme s různými dodavateli a výrobci svítidel. Čerpáme inspiraci svítidel z katalogů – Lucis.eu – Česko, Nipeko – Polsko, Nowodvorski – Polsko, Big White – Německo,Trio – Německo, Astro – Velká Britanie, které máme k dispozici při výběru přímo ve vašem interiéru. Poradíme jak postupovat při výběru osvětlení a svítidel, provedeme konkrétní výběr a při realizaci zajistíme dodávku i instalaci. V případě potřeb provedeme i rekonstrukci elektroinstalace vč. návrhu a zkreslení plánu rozvodů." />
            <Block isRight={true} image="/static/osvetleni/lucis.jpg" heading="Svítidla LUCIS" text="Svítidla LUCIS – český výrobce svítidel se řadí mezi renomované evropské výrobce. Společnost byla založena v roce 1999 v Brně. Slovo LUCIS pochází z latinského slova lux, což v překladu znamená – světlo, světlý, zářící. Od počátku své existence spolupracuje s mladými designéry a výroba svítidel probíhá v dílnách předních českých sklářů. Hlavním prvkem je ručně foukané trojvrstvé opálové sklo, jímž se svítidla LUCIS jednoznačně odlišují od ostatní průmyslové výroby – https://www.lucis.eu/cz/" />
            <Block isRight={false} image="/static/osvetleni/osvetleni.jpg" heading="Osvětlení" text="Nejen způsob, ale také intenzita osvětlení je důležitým faktorem. Osvětlení je individuální záležitostí, důležitý je projekt domu nebo bytu, uspořádání místností a styl a design bydlení. Osvětlením v interiéru dokreslíme atmosféru, která by měla být v souladu s životním prostředím a vytvářet vhodné prostředí pro práci i odpočinek. Každá místnost má své individuální požadavky na osvětlení. Platí – čím větší je svítidlo, tím slabší jsou stíny, které vrhá a naopak. Abychom vytvořili příjemnou pohodu, je třeba v každé místnosti vhodně kombinovat osvětlení centrální (nazývá se také hlavní), funkční (na čtení, na práci v kuchyni, v koupelně u zrcadla apod.) a osvětlení náladové." />
            <Block isRight={true} image="/static/osvetleni/vyber.jpg" heading="Výběr svítidel" text="Při výběru svítidla dbáme na rozměry a materiály výrobku, které se často kombinují, výjimkou není spojení matného nebo mléčného skla s kovem, plastu a barevného skla. Vhodné je volit materiály, které už máme v interiéru, případně hledáme tvarovou shodu. Při výběru osvětlení např. pro čtecí a pracovní kout volíme raději kvalitnější zdroj světla, který šetří zrak. Zároveň dbáme na to, aby světlo neoslňovalo a mělo teplý zlatavý podtón, který je očím příjemnější než studené světlo. V současné době se svítidla vyrábějí v kolekcích, které zahrnují různé varianty od jednoho typu, takže není problém je sladit. Volit můžeme mezi pevným a pohyblivým světlem." />
            <Block isRight={false} image="/static/osvetleni/kuchin.webp" heading="Kuchyně" text="Kuchyně je místo, které se považuje jak za obytné, ale především za pracovní místo v domácnosti. Vždy použijeme hned několik druhů osvětlení. Centrální osvětlení, lustr či zářivku, umístěné na stropě místnosti k osvětlení celého prostoru, bodovky pro nasvícení pracovní plochy i světla v digestoři k osvětlení varné desky. Do kuchyňského interiéru lze použít svítidla jak v teplé, tak ve studené bílé barvě světla. Trendem poslední doby je používat LED osvětlení. Ideálně se hodí světla zasazená do horních skříněk, která neoslňují a zároveň svítí kolmo na pracovní plochu. 9 - v článku - osvětlení - jídla. xx Jídelní kout je místo, kde se odehrává společný život rodiny a světlo tu hraje významnou roli. Nad stoly delší než 3 m je vhodnější centrální podélné svítidlo s několika zdroji světla s možností regulace výšky a intenzity svítivosti. Vhodné je centrální svítidlo ještě doplnit menšími např. nástěnnými světly. Pokud kuchyňský interiér je propojen i s jídelnou, je třeba řešit osvětlení pro oba interiéry tak, aby na sebe svítidla navazovala." />
            <Block isRight={true} image="/static/osvetleni/obyvak.webp" heading="Obývací pokoj" text="Obývací pokoj je nejdůležitější místnost v celém bytě. Nejlepší volbou je osvětlení v teplé bílé barvě, pro útulnější vzhled. Místnost lze dokombinovat mimo klasického osvětlení doplňkovými svítidly jako jsou stojací lampy, nástěnná světla nebo podhledová svítidla. Lze použít i nepřímé osvětlení – například svítidlo na nábytkové stěně nebo LED pásků, nebo využít stmívače světel – tedy automatické regulace jasu. Instalováním světelné soustavy z jedné kolekce dosáhneme žádaného designového efektu a nasvícením z více zdrojů docílíme optického rozčlenění místnosti." />
            <Block isRight={false} image="/static/osvetleni/loznice.webp" heading="Ložnice" text="Osvětlení v ložnici by mělo vytvořit světelnou atmosféru interiéru. Při umístění svítidel je důležité také umístění vypínačů – u dveří pro hlavní osvětlení a co nejblíže posteli pro doplňková osvětlení, vše v teplé bílé barvě. Je vhodné použít svítidla stropní nebo závěsná, na doplňkové – stolní dotykové lampičky či jednobodové svítidlo. Pokud je v ložnici pouze postel, není zde třeba hlavního světla, ale je výhodné již od vstupu ovládat lampičky u postele. Je-li v místnosti i úložný prostor, pak by měl být dostatečně osvětlen – svítidla přímo do skříní." />
            <Block isRight={true} image="/static/osvetleni/detsky-pokoj.webp" heading="Dětský pokojíček" text="Centrální svítidlo do dětského pokoje by mělo svítit v teplé bílé barvě a dostatečně intenzivně pro bezpečnou atmosféru pokoje. Velmi důležité je osvětlení pracovního stolu, jak přírodní zdroj – okno, tak umělý zdroj – lampička. Lampička by měla být polohovatelná a osvítit celý stůl. V případě praváků má dopadat světlo z přední či levé strany, u leváků naopak, a to pod úhlem 60 až 70 stupňů. Dalším svítidlem, které by v dětském pokoji nemělo chybět je lampička u postele. Je třeba přihlédnout i k věku dítěte a jeho potřebám – každý věk má svá specifika. Pro batolata jsou vhodná svítidla se zdrojem osvětlení s nízkým výkonem, jejichž svit dítě neruší při usínání nebo ve spánku." />
            <Block isRight={false} image="/static/osvetleni/koupelna.webp" heading="Koupelna" text="V koupelně platí – bezpečnost na prvním místě a dostatek světla je v podstatě nutností. Svítidla v koupelně mají krytí proti odstřikující vodě, tj. jsou označena písmeny IP. Koupelna by měla mít centrální světlo, které je možné doplnit dodatečným osvětlením. Lokální světlo se pak umístí nad zrcadlem, nebo podél zrcadla a nemělo by oslňovat. Koupelny neslouží pouze k očistě, ale i k relaxaci." />
        </>
    )
}

export default LampsAndLights